# Generated by Django 3.0.7 on 2021-03-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('post_type', models.CharField(choices=[('Doubt', 'Doubt'), ('News', 'News')], max_length=5)),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(default='feed/default.jpg', upload_to='feed/')),
            ],
        ),
    ]
