# Generated by Django 3.1.7 on 2021-03-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_request_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='from_user',
        ),
        migrations.DeleteModel(
            name='request',
        ),
        migrations.DeleteModel(
            name='resource',
        ),
    ]
