# Generated by Django 3.1.7 on 2021-03-06 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='head',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='from_user',
        ),
        migrations.AddField(
            model_name='feed',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, default='feed/default.jpg', null=True, upload_to='feed/'),
        ),
    ]
