# Generated by Django 3.0.7 on 2021-03-07 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210307_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='home.Feed'),
        ),
    ]
