# Generated by Django 3.1.7 on 2021-03-06 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YrBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('branch', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('subject_name', models.CharField(default='', max_length=100)),
                ('visibilty', models.BooleanField(default=True)),
                ('yr_branch', models.ManyToManyField(to='resources.YrBranch')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_attachment', models.FileField(upload_to='')),
                ('cost', models.IntegerField(default=0)),
                ('title', models.CharField(default=0, max_length=100)),
                ('buyer', models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='bought_resources', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='liked_resources', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject')),
            ],
        ),
    ]
