# Generated by Django 3.1.7 on 2021-03-06 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_attachment',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='pdf_file',
            field=models.FileField(default='', upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='resource',
            name='preview',
            field=models.FileField(default='', upload_to='preview/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
